# Note: With the introduction of workspaces we recommend using workspaces with APIOps when possible to limit what can be extracted whenever possible. 
# More information about workspaces can be found here https://learn.microsoft.com/en-us/azure/api-management/workspaces-overview

 apiNames:
  - api1

 backendNames:
  - ignore

 diagnosticNames:
  - ignore

 groupNames:
  - ignore

 loggerNames:
  - ignore

 namedValueNames:
  - ignore

 productNames:
  - ignore

 subscriptionNames:
  - ignore

 tagNames:
  - ignore
  
 policyFragmentNames:
  - ignore